version: "2"
run:
  timeout: 10m
  tests: true
linters:
  default: standard
  enable:
    - bodyclose
    - nolintlint
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
  exclusions:
    presets: []
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - gci
    - golines
  settings:
    gofumpt:
      extra:
        group-params: true
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/tibeahx/OpenRHP)
      custom-order: true
    golines:
      max-len: 100
